<?php

namespace ProftpBundle\Repository;

/**
 * FtpgroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FtpgroupRepository extends \Doctrine\ORM\EntityRepository
{
}
