<?php

namespace ProftpBundle\Repository;

/**
 * FtpgroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FtpgroupRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @var int
     *
     */
	private $minimum_gid = 10001;

    public function getNextGroupId() {
        $nextid = $this->createQueryBuilder('g')
            ->select('MAX(g.gid) + 1')
            ->getQuery()
            ->getSingleScalarResult();

        if ( is_null($nextid)) $nextid = $this->minimum_gid;
        return $nextid;
    }
}
