<?php

namespace ProftpBundle\Repository;

/**
 * FtpgroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FtpgroupRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNextGroupId() {
        $nextid = $this->createQueryBuilder('g')
            ->select('MAX(g.gid) + 1')
            ->getQuery()
            ->getSingleScalarResult();

        if ( is_null($nextid)) $nextid = 10001; 
        return $nextid;
    }
}
