<?php

namespace ProftpBundle\Repository;

/**
 * FtpuserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FtpuserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNextUserId() {
        $nextid = $this->createQueryBuilder('u')
            ->select('MAX(u.uid) + 1')
            ->getQuery()
            ->getSingleScalarResult();
       
        if ( is_null($nextid)) $nextid = 10001; 
        return $nextid;
    }
}
