<?php

namespace ProftpBundle\Repository;

/**
 * FtpuserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FtpuserRepository extends \Doctrine\ORM\EntityRepository
{
}
